### ISSUE TITLE
Make caps lock turn on by double typing shift

### ISSUE THREAD

**Issue by iprok** [UltimateHackingKeyboard/firmware#138]
Just as it's done now for Mouse,  Mod and Fn buttons it will be great if we can "lock" shift button. If we press shift twice it should make caps lock on.

**Comment by mondalaci** [comment]
Thanks for the idea!

We only implement general features, and the generalization of this feature is to make modifiers lockable by double-tapping them.

However, this would introduce more problems than it solves. According to the feedback we receive, some users are outright frustrated by the double tap to lock layer feature because it locks layers unintentionally from time to time.

That's why we'll implement (actually largely implemented) per-key double tap to lock layer functionality, so that users will be able to enable/disable double tap to lock layer on a per key basis.

We could do the same for the double tap to lock modifiers feature, but based on the feedback we receive, I'm confident that the double tap to lock layer feature is much more often used than the double tap to lock modifier feature would be because nobody has ever requested the latter.

The main problem is that we'd have to add an additional user facing option for a feature which would be used by almost noone. This would make Agent harder to use for everyone whilst benefitting few.

I'm tagging this feature as an exotic feature and closing it. Such features will be reconsidered later. Feel free to follow up in the comments.

**Comment by kareltucek** [comment]
@mondalaci isn't the general modifier lock effectively solved by 617 in base layer?

Of course, shift-lock is apparently not same thing as caps lock... but I feel the nature of the problem is closely related...

I am also wondering whether requests like this could be solved by introducing some higher-level abstraction. (E.g., introducing double tap as a general trigger (e.g., like secondary-action-trigger and single-tap-trigger), and introducing layer toggle as an ordinary action (just like send-scancode-action))

I do not imply that this should be high priority issue. However, planning future implementation of exotic features via global generalizations seems much less problematic and more efficient in the long run than hot-fixing urgent-user-needs as special cases...

**Comment by mondalaci** [comment]
https://github.com/UltimateHackingKeyboard/agent/issues/617 doesn't solve this one. It enables modifiers to have their own layers, but Caps Lock cannot be triggered this way.

As a developer, I appreciate the kind of abstractions that you suggest. It's nice to compose primitives to achieve anything. That's what https://github.com/qmk/qmk_firmware or https://github.com/keyboardio/Kaleidoscope do with hooks and plugins. However, I don't consider them to be a great solution usability-wise.

Agent is so easy to use because it offers practical features in an intuitive manner. By exposing every possible combination of every feature the UI would become vastly more complex, and most of the options offered woudn't make practical sense. I'd much rather never implement the least used 1% of features than overwhelm users with extra features they almost certainly won't ever use.

**Comment by kareltucek** [comment]
I've been thinking some time if I should post this at all, and how to formulate the points. Sorry if it's too long or too irrelevant or too critical. Also, I am totally aware that the final proposal is a complex one with respect to implementation.

Regarding mod locking: 
-----------------------
I was asking just because you seem to have claimed that regular-modifier locking is not planned to be implemented. Yet I do not see how #617 can be implemented without allowing it as a side effect (for regular modifiers).

If we assume that #617 allows locking other modifiers, then you could try to extended the support to caps lock too. Indeed, Caps Lock can be easily handled as a modifier (such modifier would send virtual caps lock tap on keydown, virtual tap on keyup; respectively, three times virtual caps-lock-tap on double tap). 

This might be a clean-with-respect-to-UI work-around-ish solution, which however I am *not* proposing. 

Regarding abstractions:
----------
I've been thinking about this for some time, however, I still fail to spot the possible UI clutter/complexity implied by such request. At least if implemented the way I have in mind. Namely, I am not proposing "exposing user to every possible combination" *explicitly*. On the contrary, I am proposing a refactor which would decouple the concept of an action from the concept of a trigger. I see it as a simplification of things, since the current UI presents user exactly with concrete combinations, making the set of achievable configurations hardly predictable.

I will try to formulate the vision, since we most likely do not understand each other.

The main idea is to decouple the concept of triggers (e.g. single-tap-trigger, secondary-action-trigger, double-tap-trigger) from the concept of actions (e.g., send-keycode, move-mouse, click-mouse, execute-macro) and to allow any action to be combined with any trigger. Note that if we understand actions as properties of triggers, and actions are search-driven (just as scancodes are now), then user has to explicitly input any unusual combinations. I.e., this on the contrary prevents any need to explicitly "expose user to every possible combination". 

By default, only basic set of actions would be provided (scancodes, mouse actions, macro actions, one or two default parametrisations of layer switching.) by means of searchable dropdown boxes. Less usual actions would be provided by means of macros, since macros are exactly composite actions (i.e., have nothing to do with triggers).

This proposal would imply:
- making firmware and format enough versatile to handle such layouts. Yes, the implementation would most likely be a problem if you did not think in the generic terms at the beginning.
- generalizing the first tab of remap dialog a bit so that it would handle both its current purpose and the advanced requirements
- reformulating the first tab so that it is better structured.

For instance, clean and intuitive UI could look like this:
![trigger/action oriented configurator](http://www.ktweb.cz/uhk/uhk5.png)

In order to remove any unneeded complexity for undemanding users, the obscure and otherwise unneeded slots could be hidden by default via some sort of check box, so the result could look simply like this:

![trigger/action oriented configurator](http://www.ktweb.cz/uhk/uhk2.png)

summed up:
- The current many-tab configuration is indeed very intuitive, yet in my opinion strongly couples triggers with actions and therefore limits the combinations user can input.
- The current many-tab configuration should still be there for convenience. It would simply provide a way to simply configure most common use cases. 
- Generalization of the first tab would simply make it much more powerful, therefore providing alternative way of achieving the same (and more). Without increasing complexity of configuration of the present features.
- The macro engine should allow performing all actions with all possible parametrisations. This would imply that all parametrisations could be achieved from the first tab (via search) without flooding the user with many combinations. This way, actions shown to the user as available for a trigger could be just the sensible ones.
- As a bonus, this allows simple integration of new exotic features into the interface. More complex features could be accessible as actions in in the macro creation tool (and nowhere else), and interfaced to the user via trigger slots. 

put another way I am claiming that:
- I am just proposing a refactor decoupling actions from triggers. 
- I believe that having triggers coupled with actions in principle leads to unexpected issues with many unusual-yet-sensible configurations.
- The achievable set of configurations is not predictable. 

Btw, just during the last month, I have noticed three different exotic-feature requests which would all be solved by this refactor. If we assume that only one in five users is active enough to report a feature he is lacking...

Regarding qmk/kaleidoscope:
------------
I've went through the links and if I understand correctly, both are intended to be configured mainly via source code. As long as we are talking about UI complexity, I do not find them relevant (should I?).

Regarding QMK, I have found an extremely simple web configurator, which for some reason understands triggers as properties of actions, therefore serving exactly "every possible combination". Not the way to go. I see no non-basic feature here.

Regarding kaleidoscope, I have found no graphical configurator at all.

Rationale:
-------
One question probably presents itself: why do we need obscure slots and multi functional buttons at all? For me, the reason is simple: the keyboard hardware features too few hardware buttons.

- chording every non-alpha-numeric key is impractical
- some use cases require specific set of non-alpha-numeric keys in one layer (i.e., I need arrow keys, F keys and esc in one layer for gaming. I need standard alphanumeric keys for text editting in one layer. I might need mouse-related functionality with specific keys in one layer for some specific apps.)
- The Super key (or fn key in my setup) is hard to reach, so I cannot map anything useful in there. (As a result, only three easily reachable layers are available, which have to cover all alphanumeric keys, non-alphanumeric keys, mouse, and any possible nonstandard needs. As a result, mapping only a normal keyboard layout into UHK is pain.)
- There is not enough easily reachable keys to cover even three layers in a symmetric fashion without having enter as secondary mouse role. 
- I want the keyboard itself to remain intuitive, which means; 1) Keeping as much standard functionality at standard places possible. 2) Not creating a specific layer for every program I use.

Usability-wise, I really wish you had included one more (esc, f1-f12) hardware row and probably one more hardware column on the right side of keyboard...

**Comment by mondalaci** [comment]
@kareltucek Thank you for taking the time to create this very detailed writeup.

The locking of modifier layers will be possible, however the modifiers themselves won't be composed, only if the key action contains the modifier in question. This allows for greater configuration freedom.

Caps Lock by definition is not a modifier. It does not compose with other keys, so treating it like one doesn't feel right.

Regarding the UI, I can see your point, and I think you did a great job of laying out the single-tap, double-tap, and secondary role actions in the key action popover. I also understand the concepts of separating actions from triggers.

Yet, I think yours is a great example how introducing more features can make Agent less intuitive. The UI is more cluttered, even when double-tap action and secondary role action is collapsed, but the new content of the select2 boxes would be even more confusing as it'd overlap with the the features of other tabs of the key action popover. It'd also contain useless combinations like move mouse left on double tap.

I mentioned QMK and Kaleidoscope to exemplify composability via code. They don't have any reasonable UIs, indeed.

Regarding the rationale part your comment, I think yours is a critique of 60% layouts in general. This is hardware issue, not a software issue. We plan to design a 80% UHK in the future containing dedicated Esc, F{1-12} keys and a navigation cluster.

> I am just proposing a refactor decoupling actions from triggers.

You're talking about this like it's a simple thing. It is not. In practice, your proposal would blow up the whole firmware and Agent codebase. It'd affect everything very deeply and would take forever to implement. Then another 1% of users would eventually create further exotic feature requests, calling for another monumental refactor that would call for enormous work to create little value for a very small group while making things more complex for everyone else.

Please let's keep the conversation conscise going forward. It's extremely difficult to follow so many points.

**Comment by kareltucek** [comment]
> Yet, I think yours is a great example how introducing more features can make Agent less intuitive.

I do not see that, sorry.

>the new content of the select2 boxes would be even more confusing as it'd overlap with the the features of other tabs of the key action popover. It'd also contain useless combinations like move mouse left on double tap.

Well, determining what exactly should be shown where is an implementation detail, which I think does not need detailed discussion at this time&place.

The example in question indeed has rather limited use. However, as long as the box is search driven, I generally do not see a problem in it. It already contains so many items that picking them by hand does not make sense and If the user explicitly asks software to do something, who are we to oppose him? 

> This is hardware issue, not a software issue.

Yes, definitely.

>We plan to design a 80% UHK

Great!

> You're talking about this like it's a simple thing. It is not. 

Well, I am simply discussing the points you keep putting forward as a problem, which is always the UI. 

> In practice, your proposal would blow up the whole firmware and Agent codebase.

Well, what should I say to this? I guess that claiming what you did right or wrong is not very constructive at this point. 

You are the master of your implementation and so you are the most likely one to come up with possible solutions to technical problems. I definitely see that this is a problem, and am neither claiming nor sure myself whether it is worthwhile. I can say only that I see the current state as conceptually wicked.

It is definitely up to you whether you decide to set this as a long term goal or not. I can only suggests that it usually helps to take some time to think of how to achieve things in the easiest possible fashion, rather than to take time to think up reasons why the things are impossible :-).

I definitely do not anticipate that you will agree to implementing things like this on a spot. It is rather a point for long term consideration in context of other problems and feature requests which pop up.

Honestly, I am also very curious about the macro engine which should be available soon, since seeing it will answer many question regarding actual strength and configurability of UHK.

**Comment by mondalaci** [comment]
I'm not saying it's impossible. I'm saying that it's a huge amount of work that would result in a little gain for some and a net negative for everyone else.

I don't want to sound unconstrictive. Quite frankly, I'm rather overwhelmed nowadays, and can't sufficiently concentrate on this issue. Let's talk about it later.

**Comment by kareltucek** [comment]
Sure

**Comment by owlstead** [comment]
I'm all for making a less cluttered UI. However I side with kareltucek on thinking that double tapping shift is a great *and commonly used* way to switching on CAPS. All the keys on the base layer are basically the same as on *any* QWERTY keyboard *except the CAPS key* which has become the mouse key. So in this case UHK is the one introducing a one-off feature, not the users.

So personally I would seriously consider making double clicking shift a specific option for each key map. Leaving it on by default would probably break gaming though, so it should not be a default (!). Don't fuck with Strafe or you'll get whacked by a frustrated FPS freak :)

Otherwise yeah, enable double clicking to perform *any* action per key is the only configurable option that seems to make sense.

Just my 2cts. I cannot vote on features it seems, and I think the note about gaming helps talk about this "exotic" feature.

**Comment by LazaroFilm** [comment]
Might I add that the iPhone uses double tapping the shift key for CapsLock. I know it's not a mechanical keyboard, but in term of number of user of the function you can't beat that. I would also like to add my voice to that feature request. Also, on iPhone it's double tap to activate CapsLock and single tap to deactivate it.
