### ISSUE TITLE
secondary layer switch not working if next key also has secondary layer switching on the base layer

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#152]
Firmware 8.2.5, Agent 1.2.5.

Configuration - Base Layer
CapsLock: primary = keypress "Backspace"; secondary = layer switch to Mod layer
Left Space: primary = keypress "Space"; secondary = layer switch to Mouse layer

Configuration - Mod layer
Left Space: keypress "Enter" (no secondary function)

Configuration - Mouse layer
CapsLock: keypress "Enter" (no secondary function)

When I hold down CapsLock and press Left Space, I would expect an Enter keypress. Instead, nothing happens, and when I release CapsLock I get Backspace.

When I hold down Left Space and press CapsLock, I would expect an Enter keypress. Instead, nothing happens, and when I release Left Space I get Space.

I am not sure if this has already been fixed as part of #149 or #125, but want to record it for now so it can be retested.

**Comment by mondalaci** [comment]
Please always test the most recent firmware version which is currently 8.4.2. I'm closing this assuming that this has been fixed, and will reopen if needed.

**Comment by mondalaci** [comment]
As a rule of thumb, please always report issues against the latest firmware version. As you can see, the referenced issues are already closed.

**Comment by mhantsch** [comment]
Well, you now got me to switch to the prelease / alpha versions, download and update to firmware 8.4.2, and the issue still occurs. Sorry, but I think you need to re-open this one.

**Comment by mondalaci** [comment]
I can reproduce this issue. Thanks for reporting! Assigning to @eltang.

**Comment by mondalaci** [comment]
Fixed in firmware 8.4.4

**Comment by mhantsch** [comment]
Yes, I can confirm this is fixed in 8.4.4.
