### ISSUE TITLE
Freeze bug

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#172]
Firmware versions larger than 8.2.5 sometimes freeze. When it happens, your UHK gets unresponsive all of a sudden. Your UHK may not be affected at all, or it can take hours, days or even weeks for the freeze to hit.

The reason we haven't yet fixed this bug is because it happens so rarely, and only on certain UHKs. We need your feedback, so if you're reading this please update to [firmware 8.4.5](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.4.5) via Agent.

If your UHK freezes, run the following script and paste its output to provide diagnostics information, so that we can hopefully figure out what the hell is going on. (You'll need another keyboard to do this if your UHK froze).

Pull the [Agent repo](https://github.com/UltimateHackingKeyboard/agent) and build it. Then run `packages/usb/get-debug-info.js`. It'll output something like this:

```
I2cWatchdog:919988055 | I2cSlave:306651339 | I2cWatch:950237 | I2cRecovery:0 | KeyMatrix:783778471 | UsbReport:157778114 | Time:101366130 | UsbGeneric:237 | UsbBasic:41632 | UsbMedia:252 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:919997815 | I2cSlave:306654592 | I2cWatch:950247 | I2cRecovery:0 | KeyMatrix:783783350 | UsbReport:157782993 | Time:101367237 | UsbGeneric:238 | UsbBasic:41632 | UsbMedia:252 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920007573 | I2cSlave:306657846 | I2cWatch:950257 | I2cRecovery:0 | KeyMatrix:783788300 | UsbReport:157787816 | Time:101368361 | UsbGeneric:239 | UsbBasic:41640 | UsbMedia:252 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920017331 | I2cSlave:306661098 | I2cWatch:950267 | I2cRecovery:0 | KeyMatrix:783793238 | UsbReport:157792640 | Time:101369482 | UsbGeneric:240 | UsbBasic:41644 | UsbMedia:252 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920027090 | I2cSlave:306664351 | I2cWatch:950277 | I2cRecovery:0 | KeyMatrix:783798182 | UsbReport:157797462 | Time:101370593 | UsbGeneric:241 | UsbBasic:41644 | UsbMedia:256 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920036849 | I2cSlave:306667604 | I2cWatch:950287 | I2cRecovery:0 | KeyMatrix:783803092 | UsbReport:157802316 | Time:101371711 | UsbGeneric:242 | UsbBasic:41644 | UsbMedia:258 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920046607 | I2cSlave:306670858 | I2cWatch:950297 | I2cRecovery:0 | KeyMatrix:783808105 | UsbReport:157807084 | Time:101372838 | UsbGeneric:243 | UsbBasic:41644 | UsbMedia:269 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920056367 | I2cSlave:306674110 | I2cWatch:950307 | I2cRecovery:0 | KeyMatrix:783812989 | UsbReport:157811962 | Time:101373962 | UsbGeneric:244 | UsbBasic:41644 | UsbMedia:270 | UsbSystem:4 | UsbMouse:110380
I2cWatchdog:920066125 | I2cSlave:306677364 | I2cWatch:950317 | I2cRecovery:0 | KeyMatrix:783821101 | UsbReport:157814081 | Time:101375047 | UsbGeneric:245 | UsbBasic:41644 | UsbMedia:270 | UsbSystem:4 | UsbMouse:110531
I2cWatchdog:920075884 | I2cSlave:306680616 | I2cWatch:950327 | I2cRecovery:0 | KeyMatrix:783831414 | UsbReport:157814333 | Time:101376086 | UsbGeneric:246 | UsbBasic:41644 | UsbMedia:270 | UsbSystem:4 | UsbMouse:110783
I2cWatchdog:920085643 | I2cSlave:306683869 | I2cWatch:950337 | I2cRecovery:0 | KeyMatrix:783838898 | UsbReport:157816997 | Time:101377160 | UsbGeneric:247 | UsbBasic:41644 | UsbMedia:270 | UsbSystem:4 | UsbMouse:110904
```

One line will be displayed per second. Most variables should be incrementing all the time automatically, but you'll have to manually increment some. Make sure to increment `UsbBasic` by typing regular scancodes on your UHK. Make sure to increment `UsbMedia` by typing media scancodes (for example volume up and down) on your UHK. Make sure to increment `UsbMouse` by mousing with your UHK. As for `UsbSystem`, you can increment it by typing system scancodes such as sleep, but this one is not terribly important. Every other variable should be incrementing automatically all the time with the exception of `I2cRecovery` which may spontaneously increment once in a while.

**Comment by joshginter** [comment]
My freezes up to this point show no output from that script. It seems like the whole HID communication gets locked up. Do you expect that to be different for other freezes?

**Comment by mondalaci** [comment]
I'm not sure, but I hope so. Otherwise folks won't be able to supply us information of what goes on inside of their UHKs without a debug probe.

**Comment by tigerkeys** [comment]
Is there a way to run the debug script under windows?  Agent under windows says Cannot write to HID device.

**Comment by mondalaci** [comment]
The debug script should work under every OS. Agent or the script says "Cannot write to HID device"?

**Comment by tuxlifan** [comment]
Could you provide the debug script as AppImage? To install npm just to provide debug info seems a bit inconvenient (not that I have yet experienced a freeze yet, but I only just upgraded the firmware...). Thanks!

**Comment by joshginter** [comment]
Agent gets a little red error "toast" in the app that has that message. It happened unexpectedly otherwise I'd have tried to take a screen shot.

**Comment by mondalaci** [comment]
@tuxlifan Thanks for the idea! We'll look into it.

@ert78gb Is there a way to add the agent/packages/usb/get-debug-info.js script to the AppImage, so that users can easily execute it without building Agent? I assume it's problematic because it depends on node and libraries, so I don't think there's an easy way.

@joshginter When does this toast error happens? Totally random or upon freezes? Do you remember the message?

**Comment by ert78gb** [comment]
@mondalaci We could add `agent/packages/usb/get-debug-info.js` to the AppImage or any package, but this js file is not enough. Need the `agent/packages/usb/uhk.js` and the whole `node_modules` folder.

The whole `node-hid` package and the usb handler codes deployed in the `app.asar` file. I think duplicate everything is not a good solution. 

I suggest to create a command line argument `--freeze-debug-info=true` and when it passed to the agent app it will start to write the debug info into the console instead of start the ui.

**Comment by mondalaci** [comment]
@ert78gb Great idea! I think we should rather wait until the next monthly update though. I'll ask people to share their experience regarding the freeze. It may turn out that it's a non-issue on every but a handful of UHKs which are faulty in some ways.

**Comment by joshginter** [comment]
Sorry. I confused this case and the old one. I originally thought you were asking me about the error because I mentioned in in my previous report on my most recent failure. I only saw it when I unplugged the frozen UHK. Sorry for the confusion.

**Comment by mondalaci** [comment]
@joshginter No problem, appreciate your feedback!

**Comment by Jopie01** [comment]
Got a freeze yet, but during an update of my Fedora Linux. The dmesg shows that the USB disconnected:
` usb 4-1: USB disconnect, device number 4`

Then messages show up:
```
[ 8332.839477] usb 4-1: new full-speed USB device number 5 using ohci-pci
[ 8332.979473] usb 4-1: device descriptor read/64, error -62
[ 8333.234446] usb 4-1: device descriptor read/64, error -62
[ 8333.477542] usb 4-1: new full-speed USB device number 6 using ohci-pci
[ 8333.624464] usb 4-1: device descriptor read/64, error -62
[ 8333.871453] usb 4-1: device descriptor read/64, error -62
[ 8333.979526] usb usb4-port1: attempt power cycle
[ 8334.427439] usb 4-1: new full-speed USB device number 7 using ohci-pci
[ 8334.843416] usb 4-1: device not accepting address 7, error -62
[ 8334.979391] usb 4-1: new full-speed USB device number 8 using ohci-pci
[ 8335.396418] usb 4-1: device not accepting address 8, error -62
[ 8335.396474] usb usb4-port1: unable to enumerate USB device
[ 8337.580348] usb 4-1: new full-speed USB device number 9 using ohci-pci
[ 8337.721376] usb 4-1: device descriptor read/64, error -62
[ 8337.969353] usb 4-1: device descriptor read/64, error -62
[ 8338.211351] usb 4-1: new full-speed USB device number 10 using ohci-pci
[ 8338.352406] usb 4-1: device descriptor read/64, error -62
[ 8338.600371] usb 4-1: device descriptor read/64, error -62
[ 8338.707402] usb usb4-port1: attempt power cycle
[ 8339.155356] usb 4-1: new full-speed USB device number 11 using ohci-pci
[ 8339.571340] usb 4-1: device not accepting address 11, error -62
[ 8339.707345] usb 4-1: new full-speed USB device number 12 using ohci-pci
[ 8340.123351] usb 4-1: device not accepting address 12, error -62
[ 8340.123436] usb usb4-port1: unable to enumerate USB device
[ 8348.875138] usb 4-1: new full-speed USB device number 13 using ohci-pci
```
I disconnected the keyboard, reconnected it and is worked again.

**Comment by mondalaci** [comment]
@Jopie01 Which firmware, and since how long have you been running >8.2.5 firmwares?

**Comment by Jopie01** [comment]
@mondalaci I'm using 8.4.5 since 30th of August and before that I have used 8.4.2. When I'm not using my system, I switch it completely off. This freeze happened during a normal system-update of Fedora. But I was also switching USB from one Arduino to another back and forth. I will keep an eye on it.

**Comment by mondalaci** [comment]
@Jopie01 Thanks! How often do these freezes generally occur?

@joshginter Do you happen to use a longer/different bridge cable than the one that was provided with your UHK?

**Comment by joshginter** [comment]
No. I use the included bridge cable.

**Comment by mondalaci** [comment]
@joshginter Thanks! Would you please shoot a picture of your usual setup? I'd like to see how much the cable is stretched and its close surroundings. Also, have you ever experienced chatter? Chatter and freezes might be related.

**Comment by Jopie01** [comment]
> @Jopie01 Thanks! How often do these freezes generally occur?

@mondalaci This was the first time in months. I can't say anything about the earlier freezes because I don't know the situation anymore :smile:

**Comment by joshginter** [comment]
![image](https://user-images.githubusercontent.com/4360824/45908513-d1b59700-bdb1-11e8-90a3-1e7534e51983.png)
That is my setup at work. Sometimes my phone will be between the keyboard halves. My home setup is very similar but the keyboard halves are usually connected as I find "connected" to be preferred for gaming.

Since you're worried about the bridge cable I figured I'd include a picture of the bot I carry the keyboard in. It's a snug fit and pushes the cable up a bit but certainly not in a way that should be a problem for that kind of coiled cable.
![image](https://user-images.githubusercontent.com/4360824/45908622-57d1dd80-bdb2-11e8-93dd-2d89baf11821.png)

**Comment by mondalaci** [comment]
@Jopie01 A single freeze in months... That's exactly why it's been mission impossible to fix this bug so far. :)

@joshginter Your setup looks fine to me, and I don't think it should make freezes frequent, however I noticed you mentioned that sometimes your phone is in the middle of the halves. Is there a correlation between your phone being between the halves and the freezes? Also, how frequently do you experience key chatter, if ever?

**Comment by joshginter** [comment]
I don't think there is a correlation. About half of my freezes have come at home with the keyboard connected not split. The most recent two at work came when I was signing in so my phone probably wasn't there.

I've not experienced chatter (to my knowledge) but I'm a pretty haphazard typer. So it's possible its happened rarely and I just attributed it to my shitty typing. Definitely not as common a problem as some people see in the other thread.

**Comment by mondalaci** [comment]
@joshginter When you use your keyboard merged, is the bridge cable connected? If so, would you disconnect the bridge cable while using your keyboard merged and watch for freezes?

**Comment by joshginter** [comment]
Ya I keep it connected. I can disconnect see how it goes. Though I havent been using my Pc at home a ton the last few weeks.

**Comment by mondalaci** [comment]
@joshginter Thank you! Appreciate very much the loads of feedback you've been providing.

**Comment by irwand** [comment]
fwiw, I'm still on 8.2.5 firmware, and I've seen it freezes. It's random and rare, and I don't have any insight into pattern or anything. But I'm just saying that potentially this bug is older than 8.2.5.

**Comment by mondalaci** [comment]
@irwand How rare?

I've been testing the freeze, and I find it increasingly probable that it may not be an issue at all. So far, I reproduced it about once over months. This might be a hardware issue. For example, if a user touches the pogo pins and a static discharge happens, a voltage spike may freeze the CPU. That kind of stuff.

According to my knowledge, @joshginter is the only person who experiences the freeze frequently (not sure how often).

**Comment by irwand** [comment]
good question. It's hard to say.. although I haven't had it for the past 2 weeks.. Maybe more. So it's rare enough for me, that it's not quite yet a big issue. I wanted to keep watching my issue, but I thought I should say something to this thread. If you're pretty sure it's HW voltage spike issue, why not release the new shiny firmware builds? Then more people will try them out. :) That said, I'll install the new firmware, and will watch the behavior some more.

**Comment by joshginter** [comment]
I would not describe my freezes as "frequent", just more common than anyone else... :p. Initially they were more common, but have been getting rarer and rarer. It is not inconceivable that all of my freezes may have been a result of static electricity, I get up and sit down pretty often. Though, I don't ever really touch the pogo pins nor have I ever noticed or felt a "spark" of static discharge. So it couldn't have been a lot of static discharge ever causing an issue for me.

**Comment by mondalaci** [comment]
@irwand The voltage spike is just a wild guess on my part. We'll definitely be releasing new firmware builds in the future, although improvement in this department is not expected until reproducing the issue gets possible.

@joshginter Thanks for elaborating!

Frankly, I feel embarassed about these freezes, even if they are rare, but to this date I wasn't able to reproduce them more often than once in a couple of months which makes them fixing practically impossible. I'll keep trying nonetheless.

**Comment by irwand** [comment]
no worries man. As engineers we know how hard it is to debug intermittent issues. :) One suggestion I have is to always have debug mode that we can turn on from the release, without needing to build anything. This will lower the bar for people to get more diagnostics data for hard to reproduce bugs. Like the --freeze-debug-info=true idea, except change that to --debug-info=true, and always include that in all future builds.

**Comment by mondalaci** [comment]
@irwand Yeah, but the thing is, UHKs seem to be unresponsive via USB upon freezes, in which case Agent is unable to query debug data via USB, so it may be a futile effort to implement debug capabilities in Agent itself.

**Comment by irwand** [comment]
@mondalaci Sure, but I always appreciate debugging capabilities anyway in release code, so customers are more empowered to help debug issues. Another idea is to use Fn+some-key to trigger capture of firmware state and store that state somewhere to be pulled out later. Not sure if you have a writable storage you can use or not for this purpose. Or maybe use the keymap LED to communicate data to user, although admittedly that might be kind of painful, since there's only 3 chars.. :) Do we know at this point whether it's just USB that's down or the whole firmware locked up? Next time it freezes I should play with changing the keymaps to see if firmware is somewhat functional.

**Comment by millerjl2** [comment]
When I've experienced the freezes the display was completely non-responsive.  Nothing when I hit mod, fn, mouse, caps lock, etc.  Once it locked when I was holding FN down and the fn LED was lit, but didn't respond upon being released, tapped again, or any other mod keys being pressed.

**Comment by mondalaci** [comment]
Please let me know guys whether you can connect to your UHK with Agent after it frooze. If so, the debug capability may be worthwhile.

**Comment by joshginter** [comment]
When the freeze happened for me agent gets stuck on the "loading configuration" section. Significantly more details can be found in the older issue.

**Comment by mondalaci** [comment]
@joshginter Thanks, but this should be enough. The USB communication got screwed in this case.

**Comment by luteijn** [comment]
Luckily, there are several secondary communication channels out of the keyboard, besides the usb. These could be quite useful to help debug crashed keyboard. If e.g. the Fn-led still reacts to the left Fn-key, then at least one knows the microprocessors on both halves are still running and i2c is still working. (left to read the key, send to right half, and then back to the left side to actually switch the led on. A simple script for people to follow to determine how frozen the keyboard is, would be useful too.

Ideally, I think there should be a special debug 'macro' bound to an unused Fn-layer key (on right half, so it can work without left side) and when a crash occurs, users can run the macro by pushing the key. Information could be dumped to the i2c (in a way easy to read out with a spare arduino or converted to rs232 with a board from aliexpress so people can make a set-up at home) or stored on keyboard PROM to be later read out by agent.

Once you have a documented and easy/offficial way to send (and maybe receive) internal state stuff out to i2c integrated for debug purposes with the keyboard, you also open up the hackability for people from maker/hackerspaces etc. to make their own hard and software expansions for the keyboard, freeing up capacity on your end to work on the core firmware and agent software,  the official trackball etc. expansions and new hardware variants like a non-staggered layout, or more than 60% setups...

**Comment by joshginter** [comment]
In my freezes so far nothing works. None of the layer keys result in changes to the lcd. So my money would be on such an onboard debugging system not being useful for this particular problem.

**Comment by luteijn** [comment]
If 'nothing works' after a crash, then it would be even more important to be able to just continuously dump out debug state over a secondary channel and just log it all for later forensics. There seems to be an unused uart on the first two pins of the K22F. Would have been nice if the first 4 pins were broken out to a debug header, but maybe that is not too hard to hack in. Of course, that would just cover the HW side, still would need some software  support in the form of some sort of monitor task...

**Comment by mondalaci** [comment]
I think I [fixed](https://github.com/UltimateHackingKeyboard/firmware/commit/8b69a25ddae09522fe6f1b4030f83714e66a1366) the freeze bug! Please read on.

A freeze happened to me yesterday. See [freeze-log.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2446098/freeze-log.txt)

I was mousing while the freeze kicked in. The LED display frooze. Pressing the keys didn't result in any actions. Reconnecting the halves didn't make a difference. Suspending and resuming my PC didn't make a difference either.

The keyboard and mouse USB interfaces were not working, but the generic USB interface was working, allowing me to capture diagnostics data. I2C communication, keyboard matrix scanning, and the timer were also working.

Based on the debug variables, keyboard matrix scanning was working which meant that the main loop was spinning. It also meant that UpdateUsbReports() got called from time to time, but UsbReportUpdateCounter wasn't incrementing which could only happen because UsbReportUpdateSemaphore was 0 which could only happen because one of the USB interfaces skipped a beat for some reason.

Then I exposed UsbReportUpdateSemaphore as an USB variable in firmware 8.5.0 via {get,set}-variable.js which made me able to artifically reproduce the bug by running `set-variable.js usbReportSemaphore 1` and resolve it with `./set-variable.js usbReportSemaphore 0` without reconnecting my UHK.

At that point, despite of being able to resolve the bug via the command line, the firmware was still affected, so I made UsbReportUpdateSemaphore reset if it gets stuck for 100ms in firmware 8.5.1. Then I tried to artifically reproduce the freeze again by running `set-variable.js usbReportSemaphore 1` and just as expected, the firmware recovered virtually immediately, so I couldn't reproduce the bug anymore.

The fact that I was able to access my UHK via USB and some other users weren't suggests me that there are different situations involved. Some UHKs might hard lock which may be due to a physical issue like a static discharge. I expect such issues to be unusually rare and only constrained to various environments.

Please give [firmware 8.5.1](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.5.1) a try, guys! Very interested about your feedback.

**Comment by richrd** [comment]
That sounds like brilliant news! I'm haven't experienced the freeze bug, but I've followed it closely here on github. This made me wonder what `usbReportSemaphore` actually is?
Anyway, great that the culprit seems to be have been found! :)

**Comment by mondalaci** [comment]
My understanding about `usbReportSemaphore` is somewhat limited, but according to my knowledge it's responsible for keeping the polling of the USB interfaces in sync. Without it, mouse movement would be far from smooth. I think it's also responsible to resolving a previous freeze bug. I really do hope that this time we nailed it. :)

**Comment by joshginter** [comment]
@mondalaci How would I go about testing your new functions? I want to go to version 8.5.0 where the bug is still present. And play around with recreating the freeze. I want to see if the behavior is consistent with the freezes I've seen in the past. I'll note if there are any major differences. Then I'll move to 8.5.1 and see if anything new happens.

**Comment by mondalaci** [comment]
@joshginter Sounds like a plan!

**Comment by joshginter** [comment]
I was hoping for some further instructions. Do I need a recent version of agent to use the .js files you mention? Do I need to do anything special to reach the "generic USB" interface?

**Comment by mondalaci** [comment]
You can use the aforementioned $agentDir/packages/usb/set-variable.js script after building the most recent Agent repo to artifically reproduce and resolve the freeze. But it shouldn't be required. The generic USB interface is working if Agent can talk to your UHK.

**Comment by joshginter** [comment]
Ok. I'll give it a try and let you know results/problems. Maybe tonight, but probably not until the weekend. Great work!

**Comment by mondalaci** [comment]
Thanks for your help! Really appreciated!

**Comment by irwand** [comment]
> but UsbReportUpdateCounter wasn't incrementing which could only happen because UsbReportUpdateSemaphore was 0 which could only happen because one of the USB interfaces skipped a beat for some reason.

@mondalaci  I really like that you found something there.. but it seems like the fix is a bit "hacky"? It seems that we still need to figure out why "one of the USB interfaces skipped a beat for some reason"? Again, I'm grateful for the fix, but it seems like there's something else still lurking down there.. :)  I'm running 8.5.1 now, I'll watch for this bug. Thanks man!

**Comment by joshginter** [comment]
So I did what we talked about. When the semaphore gets set to 1, the apparent behavior of the keyboard does seem to be like the freezes I've seen in the past. The usb-debug-info.js reporting information is decidedly unlike the natural freezes I've seen though. The other thing I notice is that with this forced freeze when I disconnect and and then reconnect the left keyboard half the display turns on and all 3 layer leds turn on (mod, fn, and mouse). In my natural freezes before that display would not turn back on.

The 3 diplay and 3 LEDs being on is consistent with the original failure description @mondalaci included in issue 148. So this appears to be a solution/work-around to the original issue that was described but not for the other form of issue reported by me.

Static seems to be the most likely cause of my problem. Anyone have any idea on how to safely test the idea that static discharge is causing my version of the issue?

**Comment by luteijn** [comment]
Agree with @irwand that the fix is somewhat hacky and a bit contrary to what you stated before that you don't want to more or less blindly reset the keyboard with a watchdog to recover from freezes. 

That being said, I think this is still a great step forward, and a workaround for (a sub set of) the freezes is more than welcome as a step 1 - glad you changed your mind on that :). It will hopefully result in less worry about this aspect and freeing up capacity to work on other things. Hope that it will also lead to eventually finding the underlying reasons for things getting out of sync in the first place, and perhaps finding a more 'soft' way to recover from them. Although as I mentioned before, sometimes just restarting when a protocol fails, is the best approach.

**Comment by mondalaci** [comment]
Admittedly, my understanding of the core issue is limited. However given that it only occurs once in a couple of months, I think it's a miracle that I could even implement a reliable workaround. It'd likely be ridiculously expensive to get to the bottom of this, and if my fix turns out to be as good as I expect it to be, we won't delve any deeper.

@joshginter Your freezes clearly differ from my freezes. When your UHK locks up, the USB and I2C periperals of your right half MCU seem to be down. Chances are your whole right half MCU locks up. I'll look into whether this can be solved in some way. Maybe a watchdog can reset the MCU in such a case, although even that wouldn't be ideal because your UHK would reenumerate over USB which is a noticable interruption.

Not sure how to test static discharge, especially in a safe way. We put our fair share of ESD suppressors into the UHK, but one keyboard died during EMC testing regardless. Do the freezes usually happen when you touch the male or female pogo pin connectors, or can you associate the freezes to any specific event?

**Comment by joshginter** [comment]
The two freezes I've documented on the other thread have happened right as I was sitting down (which is a situation likely to cause static build up). And typing my password. My hands were on the keys not touching the pogo pins. I think my thumb tends to sit pretty close to the "edge" of the space and mod keys. Which puts it close to the pogo pins, but definitely not touching them.

**Comment by asgeir** [comment]
Have you ruled race conditions out?

From a quick glance at the documentation it looks like USB callbacks are executed as interrupt handlers. So what happens when i.e. this handler https://github.com/UltimateHackingKeyboard/firmware/blob/master/right/src/usb_interfaces/usb_interface_system_keyboard.c#L46 preempts the main loop while it's executing something like https://github.com/UltimateHackingKeyboard/firmware/blob/master/right/src/usb_report_updater.c#L470 ?

It seems to me that the final value of UsbReportUpdateSemaphore will be undefined based on which instruction got preempted by the interrupt. Assuming that this compiles to LOAD, OR, STORE an interrupt can happen after the LOAD but before the STORE and invalidate the result from the OR operation.

Wouldn't it be safer to use atomic reads/writes or use two variables to handle the signaling? One which the interrupt handlers only read and the main loop only writes, and another which the main loop only reads and the interrupt handlers only write.

**Comment by mondalaci** [comment]
@asgeir Honestly, I'm not sure. What's your take on this @eltang?

**Comment by eltang** [comment]
@asgeir I think you might be correct. If a USB report is sent particularly quickly and the interrupt happens at some point before the STORE, then UsbReportUpdateSemaphore will be stuck with a non-zero value. To test this theory, I'll introduce some artificial delays into the code which should induce freezing if a race condition is indeed happening.

**Comment by eltang** [comment]
I added delays of various lengths but was unable to trigger any freezes. In addition, the symptoms that a race condition would cause are inconsistent with those described in #189. Given these, it's unlikely that a race condition is the problem. My current theory is that the semaphore getting stuck on a non-zero value is merely a symptom of a bug that happens deeper in the USB stack, meaning that 8b69a25 may not have any effect in the event of a real freeze.

**Comment by kbdh** [comment]
I got my UHK 2 days ago (mini batch 34) and updated the firmware to 8.5.2. My system is Debian 9.

Today there were 2 freezes. In both cases Agent wasn't able to load the keyboard configuration, it showed a message "Cannot write to HID device".

The first time it happened when I was typing on the left half of the UHK. The LED display went black. Pressing a key on either half didn't result in any action. After disconnecting and reconnecting to USB the UHK was working again.

The second time I was mousing when the freeze occured. The LED display was still showing the selected keymap and mouse layer. Pressing a key on either half didn't result in any action. The LED display didn't change when pressing MOD, Fn or Mouse. After disconnecting and reconnecting the left keyboard half the UHK was working again.

Is there anything else I could try when this happens again?

(I am still reading through all the info and instructions and so far wasn't successful to get get-debug-info.js working - it failed with "TypeError: Cannot read property 'write' of null").

**Comment by mondalaci** [comment]
Thanks for the detailed report, and sorry for the freezes!

Please try to reproduce the freezes with firmware 8.2.5.

The "cannot read..." and "cannot write" messages were displayed either because the USB generic HID interface of your UHK was frozen, or because you didn't update the udev rule that will be shipped with the upcoming Agent version.

Please keep me in the loop regarding future freezes. It's worth to reconnect the halves first to see if your UHK recovers, then try Agent to see if it works, and if all else fails, reconnect USB.

**Comment by kbdh** [comment]
Thanks for the hint about udev, that was indeed the reason for the  "TypeError: Cannot read property 'write' of null".

I had another freeze yesterday, same as the first one after typing on the left keyboard half. This time I reconnected the halves instead of reconnecting USB and the UHK recovered.

Then I had another problem, still with firmware 8.5.2: the LED display was switched off and showed no reaction when pressing MOD, Fn or Mouse. It also didn't show the selected keymap anymore. Apart from that the UHK was still working. I was able to type, mouse or switch keymaps. get-debug-info.js showed the  "TypeError: Cannot read property 'write' of null". After reconnecting the halves the LED was on again, but get-debug-info.js still showed the same error. Only after reconnecting USB get-debug-info.js was working again.

Today in the morning I installed firmware 8.2.5 and didn't have any freeze the whole day.

Edit 2018-10-18: 

The problem with the LED display switched off (but the UHK working otherwise) occurred several times during the last days with firmware 8.5.2. I found out that after reconnecting the halves or even without reconnecting the halves [Agent 1.2.11 from the releases page](https://github.com/UltimateHackingKeyboard/agent/releases) is able to find the UHK, but the Agent built from source is only able to find the UHK after reconnecting USB (reconnecting the halves is not sufficient). I tested this several times now and it was always the same. I think I was using [tree e333022](https://github.com/UltimateHackingKeyboard/agent/tree/e3330220439c380fe183ddf8dd95a7f751695030) first and am now using [tree a4e3696](https://github.com/UltimateHackingKeyboard/agent/tree/a4e3696078216bc787b682e3323d89a35a517a81) to build Agent.

**Comment by mondalaci** [comment]
Your case is quite strange. The fact that your UHK recovers after reconnecting the halves suggests that the left half freezes, not the right as it is usually the case.

Do you use the stock bridge cable that we provided?

**Comment by kbdh** [comment]
Yes, I am using the stock bridge cable.

**Comment by mondalaci** [comment]
Well, let's wait a couple days to see if your UHK freezes with 8.2.5. I don't have a better idea right now.

**Comment by ManuelLevi** [comment]
Hi everyone.

My keyboard frequently freezes.

Today, after freezing twice in an hour or two, I've updated the firmware to 8.5.2, the last version I could find to see if it would not freeze anymore. It still does.

This the best report I can give at the moment:

I was frequently changing between base, mouse and mod modes. I was browsing and I use a lot of browser shortcuts and the mouse feature on the UHK.

The LED indicators are activated when FN, MOD or MOUSE keys are pressed, in either side of the keyboard. That seems to be working.

Joining the keyboard together doesn't change the behavior.

UHK agent shows the message "Loading keyboard configuration...Hang tight!". It doesn't update after a couple minutes.

After disconnecting the keyboard, I got a message on the top right corner saying "could not read from HID device".

After connecting the keyboard again, the agent loads it in a second or two, and everything seems to be working fine again.

Hardware:
Using the cable provided with the UHK (the only one I have);
Running on a MacBook Pro with OS High Sierra 10.13.6.

**Comment by mondalaci** [comment]
Hi @ManuelLevi, thank you for your report, and sorry about this issue!

Which firmware version were you running before 8.5.2 with which you also experienced the freezes?

When your keyboard freezes, what happens when you simply reconnect the halves (but don't reconnect USB)? Does it unfreeze your keyboard?

**Comment by ManuelLevi** [comment]
Hi!

I was using the one it came with, 8.2.5 if I'm not mistaken.

That's what I meant with "Joining the keyboard together doesn't change the behavior.". Nothing changed when I reconnected the halves.

Seeing both halves have an effect on the LED's made me feel like it was the OS that decided to ignore the keyboard (maybe because it misbehaved before?). 

Could this happen?

(I just had 2 other freezes this morning)

**Comment by irwand** [comment]
@ManuelLevi, seems that your "freezes" might just be because the USB stopped working, maybe related to https://github.com/UltimateHackingKeyboard/firmware/issues/189 ? I'm on Windows though.

**Comment by kbdh** [comment]
I have used firmware 8.2.5 for two days without any freeze, but I was missing the macro functionality. So I switched back to firmware 8.5.2 and will see if it freezes again. I will probably also test the UHK with another computer and maybe try different USB ports (if that makes sense?)

**Comment by mondalaci** [comment]
@irwand I agree that @ManuelLevi is probably also affected by #189. I will follow up there.

@kbdh Testing your UHK with another computer and with different USB ports does make sense. Interested about your further findings.

Worst case scenario: We may end up replacing all the affected keyboards. According to all the freeze bug related reports we received, the failure rate is about 0.3% which we can definitely handle.

This is quite an umbrella issue, so I think I will close it in the near future. Both #189 and @kbdh's issue differ from what I have fixed. The root cause may share similarities, but still.

**Comment by mondalaci** [comment]
@Jopie01 @joshginter @kbdh @irwand Please shoot an email to support@ultimatehackingkeyboard.com guys, and include your GitHub user name and order id. I want to correlate all the available information on GitHub and our manufacturing database, and possibly get one on one with you.

**Comment by jwr** [comment]
A data point: I had freezes with 8.4.5 about once a week. I upgraded to 8.5.2 6 days ago and just had my first freeze, but this time it seems different: only the left half froze. The right half was working normally.

I was able to unplug and re-plug the left half and things were back to normal.

I find it slightly suspicious that these freezes occur after several days. I should start taking notes of the exact time.

**Comment by mondalaci** [comment]
@jwr Damn! Your report made me realize that I screwed up the I2C watchdog of the left keyboard half starting from firmware 8.4.3. Thank you so much!

Anyone who encountered with freezes which were solved by reconnecting the keyboard halves, please upgrade to the newly released [firmware 8.5.3](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.5.3). Chances are it'll fix your UHK.

**Comment by kbdh** [comment]
So far the only problem which still occurs with my UHK on firmware 8.5.3 is the one I mentioned earlier where the LED display turns off. I have now created a separate [issue](https://github.com/UltimateHackingKeyboard/firmware/issues/196) for this. 

Apart from this no more freezes with my UHK since upgrading to firmware 8.5.3. five days ago.

**Comment by rbrt86** [comment]
I'm afraid I also have the freeze bug since the beginning. Updating to 8.5.3 stopped it for a day, yesterday it came back once and now I have it again almost every 10 minutes. This also happended after upgrading to 8.4.5, first day was fine, but after that more issues. 

Unplugging and replugging the keyboard helps, I just plug it in the front USB port and about every 10 minutes when it stops responding I have to re-insert the usb cable

Note: I'm using it for work, connected to the client pc (w10) on which I do not have Admin access. Not sure if it's related to the client, maybe some USB scanning tool interferes with the keyboard or something?

**Comment by irwand** [comment]
@rbrt86 : when it freezes, does any of the LED respond to keypress? or is it completely dead?

**Comment by mondalaci** [comment]
@rbrt86 Very sorry to hear this! What do you mean by "USB scanning tool"? Do you have a specific hardware attached or software running?

**Comment by rbrt86** [comment]
@irwand having the freezebug as we speak, I can press mod, mouse or FN and all those leds light up. The keystrokes however are not registered on the pc, I can type whatever I want and nothing happens. I attached a dumb keyboard to the second front USB port and that works fine. Putting the who halves together doesnt fix the issue, reconnecting the usb temporarily is the only workaround I have right now. 

@mondalaci I connected the UHK to a workstation from the client which handles sensitive data. I do not have Admin access and I do not know if there are security measures running in the background to check for USB storage devices, I can imagine they run some sort of audit tooling somehow. No specific hardware is attached, just the keyboard and an optical mouse. I've checked windows Device Manager, it just shows up as an HID-keyboard in there and says it is functioning properly. Reconnecting the keyboard doesnt show any changes in device manager (it disappears obviously and then shows up again the same). Is there any additional debugging I can do?

**Comment by mondalaci** [comment]
@rbrt86 After the freeze kicks in, what happens if you reconnect the halves? Does it unfreeze your UHK?

**Comment by irwand** [comment]
@rbrt86 it sounds like your problem is different from this freeze issue. Your problem seems similar to issue I raised here: https://github.com/UltimateHackingKeyboard/firmware/issues/189
You might want to try plugging the keyboard to a usb hub instead of straight to the computer, and see if that helps any. It'll be a good data point.

**Comment by jwr** [comment]
Just wanted to report that since the upgrade to 8.5.3 on 2018-10-19 I did not see any freezes or issues  (writing this on 2018-10-31). The problem that affected me seems to have been fixed. :-)

**Comment by mondalaci** [comment]
@jwr Very glad to hear it! :) Thanks for your feedback!

**Comment by jfieber** [comment]
Installed 8.5.3 when it was posted.  Nothing that could be construed as a freeze since before or after the update.  (Order 39566 for reference, is there a serial number on these that I haven't noticed?)

**Comment by mondalaci** [comment]
@jfieber There's a serial number label on the PCB, but I don't advise disassembling any UHKs unless needed.

**Comment by richrd** [comment]
Today I encountered my first issue with the UHK, the left half froze, but the right half still works fine as we speak. I've had my keyboard for something like two months now.
- I have 8.5.1 on both halves of my UHK 
- Agent starts and loads fine
- UHK is connected via a USB hub which has worked fine in the past
- Any of the status leds on the left half won't light up but the segment display still shows my layout
- The freeze happened when I unplugged and then re-inserted my monitors HDMI cable into my laptop.

Unfortunately the debug script didn't find my UHK and returned null instead. This is the output I got:
```
dev 835 / 8501 : usage_page:b1f8, usage:17f
dev 45e / 39 : usage_page:2e32, usage:2f31
dev 1d50 / 6122 : usage_page:2d31, usage:2e32
dev 1d50 / 6122 : usage_page:2d31, usage:2e32
dev 1d50 / 6122 : usage_page:2d31, usage:2e32
dev 1d50 / 6122 : usage_page:2e32, usage:2f34
dev 835 / 8502 : usage_page:2d31, usage:2e32
dev 5ac / 8290 : usage_page:2d31, usage:2e32
dev 5ac / 8290 : usage_page:2e32, usage:2f35
dev 5ac / 273 : usage_page:2e32, usage:2f35
dev 5ac / 273 : usage_page:eca0, usage:310
dev 5ac / 273 : usage_page:3a35, usage:2e31
dev 5ac / 273 : usage_page:3a35, usage:2e31
/home/richard/code/oss/agent/packages/usb/get-debug-info.js:20
    device.write(uhk.getTransferData(payload));
           ^

TypeError: Cannot read property 'write' of null
    at getDebugInfo (/home/richard/code/oss/agent/packages/usb/get-debug-info.js:20:12)
    at Object.<anonymous> (/home/richard/code/oss/agent/packages/usb/get-debug-info.js:66:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Let me know if there's any other info I can provide.

**Comment by mondalaci** [comment]
@richrd Please update your UHK to the latest 8.5.3 firmware which should fix the issue.

**Comment by Nnarol** [comment]
Hi!

I have some sort of freezing bug as well. It started in 2 days after getting the UHK.
I used it with 2 laptops successfully, but when I tried to use it with a 3rd one, it froze right away.

The firmware version for both halves of the keyboard is 8.5.3 according to the UHK Agent.
The laptop it does not work with is a Lenovo y510p.

The keyboard was plugged in right before the PC booted, and the LED-s showed garbled characters during the GRUB bootloader screen. The CapsLock indicator and the triangle (whatever it stands for) was lit up.
I tried to use the arrow keys in the bootloader menu to select Windows 8.1. The menu has a countdown, which stopped immediately after I pressed Mod + j (my "Down" arrow), meaning that the PC recognized the fact that a key was pressed, although nothing else happened, the GRUB menu selection didn't move.

After bootup, no key seemed to work. The LEDs were still garbled, and turned blank after a short while.
I plugged the UHK back into the laptop it previously worked with, but the same thing happened.
Then I pulled the cable out and plugged it back again after rebooting the laptop, and ever since it works again with that laptop, but never the one I encountered the issue with.

Plugging the keyboard back into the problematic laptop, the LEDs were always completely dark from that moment on, and sometimes only the right keyboard half worked, but mostly neither.
The exact symptom was that at the time of plugging in, the LEDs correctly showed the default key map, and turned dark after pressing the first key.

All of the above observations were made with the keyboard in split mode.
With its halves joined, the LEDs light up when plugged into the problematic laptop, both halves work, although individual key presses sometimes don't register. The LEDs show anomalies when typing, some of the additional ones to those making up the letters flashing in and out, and all of them turning black after a while.
While joined, the two halves were still connected by the cable.

The cable I used was not the original one, but a 3 meters long one I bought afterwards, since I found the original way too short. I only used the original cable for about 1-2 hours before one of my colleagues took pity on me and lent me a longer one; and on most machines, the keyboard has been working fine.

An issue that may or may not be unrelated though, was that the mouse layer sometimes turned into the fn layer for short bursts and then back again, when I used a 5m long cable of the same sort. I concluded that it must have been too long for the signal to arrive between the halves with proper intensity.

**Comment by mondalaci** [comment]
@Nnarol Please give a try to the original bridge cable that we provided with the problematic laptop, and let me know how it works.

**Comment by Nnarol** [comment]
@mondalaci I could not reproduce the issue with either the original nor the 3m long cable. The only difference I can think of was that the laptop was not plugged into the wall, and was running off a battery.
It does cause a difference in how the touchpad makes the pointer move with this model, so it might not be irrelevant.
The UHK is at my workplace now, I'll have to bring the charger of the laptop next time.

**Comment by mondalaci** [comment]
@nnarol Thanks for the follow up! Noisy power supply seems to be the cause of your issue.

We've been flashing firmware 8.5.3 for a while to UHKs, and haven't received any reports that are due this bug, so I consider this to be fixed, and closing it.

**Comment by rbrt86** [comment]
> @rbrt86 it sounds like your problem is different from this freeze issue. Your problem seems similar to issue I raised here: #189
> You might want to try plugging the keyboard to a usb hub instead of straight to the computer, and see if that helps any. It'll be a good data point.

sorry for the late response, I've got myself a powered usb hub recently and I can confirm that the freezes no longer appear, apparently it was not related to the firmware!
